<?php
array (
    0 => 'ROLE_CREATE_ADEMPIMENTI',
    1 => 'ROLE_DELETE_ADEMPIMENTI',
    2 => 'ROLE_EDIT_ADEMPIMENTI',
    3 => 'ROLE_READ_ADEMPIMENTI',

    4 => 'ROLE_CREATE_AMMINISTRAZIONI',
    5 => 'ROLE_DELETE_AMMINISTRAZIONI',
    6 => 'ROLE_EDIT_AMMINISTRAZIONI',
    7 => 'ROLE_READ_AMMINISTRAZIONI',
    
    8 => 'ROLE_CREATE_ARGOMENTI',
    9 => 'ROLE_DELETE_ARGOMENTI',
    10 => 'ROLE_EDIT_ARGOMENTI',
    11 => 'ROLE_READ_ARGOMENTI',

    12 => 'ROLE_CREATE_CIPE',
    13 => 'ROLE_DELETE_CIPE',
    14 => 'ROLE_EDIT_CIPE',
    15 => 'ROLE_READ_CIPE',

    16 => 'ROLE_CREATE_CIPEODG',
    17 => 'ROLE_DELETE_CIPEODG',
    18 => 'ROLE_EDIT_CIPEODG',
    19 => 'ROLE_READ_CIPEODG',

    20 => 'ROLE_CREATE_DELIBERE',
    21 => 'ROLE_DELETE_DELIBERE',
    22 => 'ROLE_EDIT_DELIBERE',
    23 => 'ROLE_READ_DELIBERE',

    24 => 'ROLE_CREATE_FASCICOLI',
    25 => 'ROLE_DELETE_FASCICOLI',
    26 => 'ROLE_EDIT_FASCICOLI',
    27 => 'ROLE_READ_FASCICOLI',

    28 => 'ROLE_CREATE_FIRMATARI',
    29 => 'ROLE_DELETE_FIRMATARI',
    30 => 'ROLE_EDIT_FIRMATARI',
    31 => 'ROLE_READ_FIRMATARI',

    32 => 'ROLE_CREATE_MITTENTI',
    33 => 'ROLE_EDIT_MITTENTI',
    34 => 'ROLE_READ_MITTENTI',
    35 => 'ROLE_DELETE_MITTENTI',

    36 => 'ROLE_CREATE_PRECIPE',
    37 => 'ROLE_EDIT_PRECIPE',
    38 => 'ROLE_READ_PRECIPE',
    39 => 'ROLE_DELETE_PRECIPE',

    40 => 'ROLE_CREATE_PRECIPEODG',
    41 => 'ROLE_EDIT_PRECIPEODG',
    42 => 'ROLE_READ_PRECIPEODG',
    43 => 'ROLE_DELETE_PRECIPEODG',

    44 => 'ROLE_CREATE_REGISTRI',
    45 => 'ROLE_DELETE_REGISTRI',
    46 => 'ROLE_EDIT_REGISTRI',
    47 => 'ROLE_READ_REGISTRI',

    48 => 'ROLE_CREATE_RUOLICIPE',
    49 => 'ROLE_DELETE_RUOLICIPE',
    50 => 'ROLE_EDIT_RUOLICIPE',
    51 => 'ROLE_READ_RUOLICIPE',

    52 => 'ROLE_CREATE_TAGS',
    53 => 'ROLE_DELETE_TAGS',
    54 => 'ROLE_EDIT_TAGS',
    55 => 'ROLE_READ_TAGS',

    56 => 'ROLE_CREATE_TITOLARI',
    57 => 'ROLE_DELETE_TITOLARI',
    58 => 'ROLE_EDIT_TITOLARI',
    59 => 'ROLE_READ_TITOLARI',

    60 => 'ROLE_CREATE_UFFICI',
    61 => 'ROLE_DELETE_UFFICI',
    62 => 'ROLE_EDIT_UFFICI',
    63 => 'ROLE_READ_UFFICI',

    64 => 'ROLE_CREATE_UTENTI',
    65 => 'ROLE_DELETE_UTENTI',
    66 => 'ROLE_EDIT_UTENTI',
    67 => 'ROLE_READ_UTENTI',

    68 => 'ROLE_CREATE_CIPEESITI',
    69 => 'ROLE_DELETE_CIPEESITI',
    70 => 'ROLE_EDIT_CIPEESITI',
    71 => 'ROLE_READ_CIPEESITI',

    72 => 'ROLE_CREATE_CIPEESITITIPO',
    73 => 'ROLE_DELETE_CIPEESITITIPO',
    74 => 'ROLE_EDIT_CIPEESITITIPO',
    75 => 'ROLE_READ_CIPEESITITIPO',

    76 => 'ROLE_CREATE_CIPEARGOMENTITIPO',
    77 => 'ROLE_DELETE_CIPEARGOMENTITIPO',
    78 => 'ROLE_EDIT_CIPEARGOMENTITIPO',
    79 => 'ROLE_READ_CIPEARGOMENTITIPO',

);