<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdempimentiAmministrazioneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class AdempimentiAmministrazioneRepository extends \Doctrine\ORM\EntityRepository
{


}