<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use UserBundle\Entity\RelAllegatiRegistri;
use UserBundle\Entity\Allegati;

/**
 * AllegatiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */


class AllegatiRepository extends \Doctrine\ORM\EntityRepository
{
    
    
/*   public function allegatiRegistro($id) {
        
        $parameters = array ();
        $filter = "";
		$filter .= " AND r.idRegistri = :idRegistri ";
		$parameters['idRegistri'] = $id;

          
        $qb = $this->getEntityManager();

        $query = $qb
            ->createQueryBuilder()->select('r.idRegistri as id_registri,
                                           r.idAllegati as id_allegati,
                                           a.id as id,
                                           a.data as data,
                                           a.file as file'
										)
            ->from('UserBundle:RelAllegatiRegistri', 'r')
			->leftJoin('UserBundle:Allegati', 'a', 'WITH', 'r.idAllegati = a.id')
            ->where('1=1' . $filter)
            ->setParameters($parameters);
            
        //print_r($query->getQuery()->getSql());
            
        return $query->getQuery()->getResult(\Doctrine\ORM\Query::HYDRATE_SCALAR);
    }*/
    
    
	  
}
