<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AmministrazioneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */


class AmministrazioneRepository extends EntityRepository
{
	
	  public function findAmministrazione() {
        return $this->getEntityManager()
                ->createQuery('SELECT a.id FROM UserBundle:Amministrazione a')->getResult();

    }
}
