<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DelibereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class DelibereRepository extends \Doctrine\ORM\EntityRepository
{

    public function listaDelibere($limit, $offset, $sortBy, $sortType, $argomento) {
        $parameters = array ();
        $filter = "";

        if ($argomento != "") {
            $filter .= " AND d.argomento LIKE :argomento ";
            $parameters['argomento'] = '%'.$argomento.'%';
        }

        $qb = $this->getEntityManager();

        $query = $qb
            ->createQueryBuilder()->select('d.id as id,
                                            d.data as data,
                                            d.idStato as id_stato,
                                            d.numero as numero,
                                            d.argomento as argomento,
                                            d.finanziamento as finanziamento,
                                            d.note as note,
                                            d.noteServizio as note_servizio,

                                            d.foglioCC as foglio_cc,
                                            d.numeroCC as numero_cc,
                                            d.idRegistroCC as registro_cc,
                                            d.numeroGU as numero_gu,
                                            d.dataDirettoreInvio as data_direttore_invio,
                                            d.dataDirettoreRitorno as data_direttore_ritorno,
                                            d.dataMefInvio as data_mef_invio,
                                            d.dataMefRitorno as data_mef_ritorno,
                                            
                                            d.noteDirettore as note_direttore,
                                            d.noteMef as note_mef,
                                            d.noteSegretario as note_segretario,
                                            d.notePresidente as note_presidente,
                                            d.noteCC as note_cc,
                                            d.noteP as note_p,
                                            d.noteGU as note_gu,

                                            d.dataConsegna as data_consegna,
                                            d.dataSegretarioInvio as data_segretario_invio,
                                            d.dataSegretarioRitorno as data_segretario_ritorno,
                                            d.dataPresidenteInvio as data_presidente_invio,
                                            d.dataPresidenteRitorno as data_presidente_ritorno,
                                            d.dataInvioCC as data_invio_cc,
                                            d.dataRegistrazioneCC as data_registrazione_cc,
                                            d.dataInvioGU as data_invio_gu,
                                            d.dataGU as data_gu,                                       
                                            
                                            ud.idUffici as id_uffici')
            ->from('UserBundle:Delibere', 'd')
            ->leftJoin('UserBundle:RelUfficiDelibere', 'ud', 'WITH', 'd.id = ud.idDelibere')
            ->where('1=1')
            ->setFirstResult($offset)
            ->setMaxResults($limit)
            ->addOrderBy('d.data', "DESC")
            ->addOrderBy('d.'.$sortBy, $sortType);

            
        //print_r($query->getDql());
        //print_r($query->getQuery()->getSql());

        return $query->getQuery()->getResult();
    }



    public function schedaDelibera($id) {

        $parameters = array ();
        $filter = "";
        $filter .= " AND d.id = :id ";
        $parameters['id'] = $id;

        $qb = $this->getEntityManager();

        $query = $qb
            ->createQueryBuilder()->select('d.id as id,
                                            d.data as data,
                                            d.numero as numero,
                                            d.idStato as id_stato,
                                            d.argomento as argomento,
                                            d.finanziamento as finanziamento,
                                            d.note as note,
                                            d.noteServizio as note_servizio,
                                            d.scheda as scheda,
                                            d.dataConsegna as data_consegna,
                                            d.idDirettore as id_direttore,
                                            d.dataDirettoreInvio as data_direttore_invio,
                                            d.dataDirettoreRitorno as data_direttore_ritorno,
                                            d.noteDirettore as note_direttore,
                                            d.invioMef as invio_mef,
                                            d.dataMefInvio as data_mef_invio,
                                            d.dataMefPec as data_mef_pec,
                                            d.dataMefRitorno as data_mef_ritorno,
                                            d.noteMef as note_mef,
                                            d.idSegretario as id_segretario,
                                            d.dataSegretarioInvio as data_segretario_invio,
                                            d.dataSegretarioRitorno as data_segretario_ritorno,
                                            d.noteSegretario as note_segretario,
                                            d.idPresidente as id_presidente,
                                            d.dataPresidenteInvio as data_presidente_invio,
                                            d.dataPresidenteRitorno as data_presidente_ritorno,
                                            d.notePresidente as note_presidente,
                                            d.dataInvioCC as data_invio_cc,
                                            d.numeroCC as numero_cc,
                                            d.dataRegistrazioneCC as data_registrazione_cc,
                                            d.idRegistroCC as id_registro_cc,
                                            d.foglioCC as foglio_cc,
                                            d.tipoRegistrazioneCC as tipo_registrazione_cc,
                                            d.noteCC as note_cc,
                                            d.dataInvioP as data_invio_p,
                                            d.noteP as note_p,
                                            d.dataInvioGU as data_invio_gu,
                                            d.numeroInvioGU as numero_invio_gu,
                                            d.tipoGU as tipo_gu,
                                            d.dataGU as data_gu,
                                            d.numeroGU as numero_gu,
                                            d.dataEcGU as data_ec_gu,
                                            d.numeroEcGU as numero_ec_gu,
                                            d.dataCoGU as data_co_gu,
                                            d.numeroCoGU as numero_co_gu,
                                            d.pubblicazioneGU as pubblicazione_gu,
                                            d.noteGU as note_gu,
                                            
                                            ud.idUffici as id_uffici,
                                            fd.idFirmatari as id_segretariato
                                            ')
            ->from('UserBundle:Delibere', 'd')
            ->leftJoin('UserBundle:RelUfficiDelibere', 'ud', 'WITH', 'd.id = ud.idDelibere')
            ->leftJoin('UserBundle:RelFirmatariDelibere', 'fd', 'WITH', 'd.id = fd.idDelibere')
            ->where('1=1' . $filter)
            ->setParameters($parameters);


        //print_r($query->getDql());
        //print_r($query->getQuery()->getSql());

        return $query->getQuery()->getResult(\Doctrine\ORM\Query::HYDRATE_SCALAR);
    }



    public function getAllegatiByIdDelibere($id) {
        $parameters = array ();
        $filter = "";
        $filter .= " AND p.idDelibere = :id ";
        $parameters['id'] = $id;

        $qb = $this->getEntityManager();

        $query = $qb
            ->createQueryBuilder()->select('a.id as id,
                                            a.data as data,
                                            a.file as file,
                                            p.idAllegati as id_allegati,
                                            p.idDelibere as id_delibere,
                                            p.tipo as tipo
                                            ')
            ->from('UserBundle:Allegati', 'a')
            ->leftJoin('UserBundle:RelAllegatiDelibere', 'p', 'WITH', 'a.id = p.idAllegati')
            ->where('1=1' . $filter)
            ->setParameters($parameters);

        //print_r($query->getDql());
        //print_r($query->getQuery()->getSql());

        //return $query->getQuery()->getResult(\Doctrine\ORM\Query::HYDRATE_SCALAR);
        $array = array ();
        foreach ($query->getQuery()->getResult() as $item) {
            $path_parts = pathinfo($item['file']);

            $array[] = array(
                'id' => $item['id'],
                'data' => filemtime($item['file']) * 1000,
                'nome' => $path_parts['basename'],
                'tipo' => $path_parts['extension'],
                'relURI' => $item['file'],
                'dimensione' => filesize($item['file']),
                'tipologia' => $item['tipo']
            );
        }



        return $array;



    }
    
}