<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LastUpdatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class LastUpdatesRepository extends \Doctrine\ORM\EntityRepository
{

    //public function listaTitolari($limit, $offset) {
    //    return $this->getEntityManager()
    //            ->createQuery('SELECT t
    //                            FROM UserBundle:Titolari t
    //                            WHERE 1=1')->setFirstResult($offset)
    //                                       ->setMaxResults($limit)
    //                                       ->getResult();
    //}
    
}
