<?php

namespace UserBundle\Repository;

/**
 * MittenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MittenteRepository extends \Doctrine\ORM\EntityRepository
{
}
