<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RuoliCipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */


class RuoliCipeRepository extends \Doctrine\ORM\EntityRepository
{
	
	  
}
