<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class UserRepository extends \Doctrine\ORM\EntityRepository {

    public function listaUtenti() {
        return $this->getEntityManager()
                ->createQuery('SELECT u.id,
                                    u.username as userName,
                                    u.firstName as firstName,
                                    u.lastName as lastName,
                                    u.email as eMail,
                                    u.created as registrationDate,
                                    u.idUffici as id_uffici,
                                    u.cessatoServizio as cessatoServizio,
                                    u.ip as ip,
                                    u.stazione as stazione,
                                    u.idRuoliCipe as id_ruoli_cipe
                                FROM UserBundle:User u')->getResult();
    }
    
    public function schedaUtente($id) {
        return $this->getEntityManager()
                ->createQuery('SELECT u.id,
                                    u.username as userName,
                                    u.firstName as firstName,
                                    u.lastName as lastName,
                                    u.email as eMail,
                                    u.idUffici as id_uffici,
                                    u.cessatoServizio as cessatoServizio,
                                    u.ip as ip,
                                    u.stazione as stazione,
                                    u.idRuoliCipe as id_ruoli_cipe,
                                    u.created as registrationDate
                                FROM UserBundle:User u WHERE u.id = ' . $id)->getResult();
    }



}
